# -*- coding: utf-8 -*-
"""foto_descricao_genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMkHMbim4BNomRPopABqvmDDODtu5hdx
"""

from typing import List, Union

# Para a imagem
import requests
from PIL import Image
from io import BytesIO

# Para manutenção do modelo
from time import sleep
from textwrap import wrap
from google.colab import userdata
import google.generativeai as genai
genai.configure(api_key=userdata.get('GEMINI_API_KEY'))
model_name = 'models/gemma-3-12b-it'
model_RPM = 30
model = genai.GenerativeModel(model_name)

def chat(prompt: Union[List,str], verbose=True) -> Union[None,str]:
  response = model.generate_content(prompt)
  sleep(60//model_RPM)
  if verbose:
    for i in response.text.split('\n'):
      print("\n".join(wrap(i, width=140 , initial_indent='\t')))
    return None
  return response.text

# Carregar a imagem a partir de uma URL
url = "https://blog.polipet.com.br/wp-content/uploads/2024/01/pato.jpeg"
limite = (896,896)

# Redimensiona a imagem
response = requests.get(url)
img = Image.open(BytesIO(response.content))
if img.size > limite:
  img = img.resize(limite)

# Crie o prompt com a imagem e o texto
prompt_parts = [
    img,  # O objeto da imagem que carregamos
    """
    Verifique a imagem e responda caso consiga identificar,
    o tipo de animal e a raça, caso não tenha certeza informe
    'não identificado' no campo equivalente.
    Dica: O animal é um pet.
    [{ 'tipo':<animal>, 'raça':<raça> }]"""
]

display(img.reduce(4))
print('\n',"*++*"*24,'\n')
chat(prompt_parts)

